CREATE TABLE one_time_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_value VARCHAR(255),
    username    VARCHAR(255),
    expires_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_one_time_tokens PRIMARY KEY (id)
);

ALTER TABLE submissions
    ALTER COLUMN created_at DROP NOT NULL;


ALTER TABLE one_time_tokens
    ADD CONSTRAINT uc_token_value UNIQUE (token_value);