CREATE TABLE authors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname    VARCHAR(255),
    lastname     VARCHAR(255),
    email        VARCHAR(255),
    country      VARCHAR(255),
    organization VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE call_for_papers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conference_id BIGINT,
    start_date    date,
    end_date      date,
    guidelines    VARCHAR(255),
    CONSTRAINT pk_call_for_papers PRIMARY KEY (id)
);

CREATE TABLE call_for_papers_topics
(
    call_for_papers_id BIGINT NOT NULL,
    topics_id          BIGINT NOT NULL,
    CONSTRAINT pk_call_for_papers_topics PRIMARY KEY (call_for_papers_id, topics_id)
);

CREATE TABLE conferences
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    acronym        VARCHAR(255),
    venue          VARCHAR(255),
    city           VARCHAR(255),
    country        VARCHAR(255),
    first_day      date,
    last_day       date,
    primary_area   VARCHAR(255),
    secondary_area VARCHAR(255),
    organizer      VARCHAR(255),
    phone_number   VARCHAR(255),
    other_info     VARCHAR(255),
    user_id        BIGINT,
    CONSTRAINT pk_conferences PRIMARY KEY (id)
);

CREATE TABLE documents
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename  VARCHAR(255),
    file_type VARCHAR(255),
    data      OID,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

CREATE TABLE keywords
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content VARCHAR(255),
    CONSTRAINT pk_keywords PRIMARY KEY (id)
);

CREATE TABLE submissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title         VARCHAR(255),
    description   VARCHAR(255),
    document_id   BIGINT,
    conference_id BIGINT                                  NOT NULL,
    is_evaluate   BOOLEAN,
    is_validate   BOOLEAN,
    CONSTRAINT pk_submissions PRIMARY KEY (id)
);

CREATE TABLE submissions_authors
(
    submission_id BIGINT NOT NULL,
    authors_id    BIGINT NOT NULL
);

CREATE TABLE submissions_keywords
(
    submission_id BIGINT NOT NULL,
    keywords_id   BIGINT NOT NULL,
    CONSTRAINT pk_submissions_keywords PRIMARY KEY (submission_id, keywords_id)
);

CREATE TABLE topics
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content VARCHAR(255),
    CONSTRAINT pk_topics PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE call_for_papers
    ADD CONSTRAINT uc_call_for_papers_conference UNIQUE (conference_id);

ALTER TABLE call_for_papers_topics
    ADD CONSTRAINT uc_call_for_papers_topics_topics UNIQUE (topics_id);

ALTER TABLE conferences
    ADD CONSTRAINT uc_conferences_user UNIQUE (user_id);

ALTER TABLE submissions_authors
    ADD CONSTRAINT uc_submissions_authors_authors UNIQUE (authors_id);

ALTER TABLE submissions_keywords
    ADD CONSTRAINT uc_submissions_keywords_keywords UNIQUE (keywords_id);

ALTER TABLE call_for_papers
    ADD CONSTRAINT FK_CALL_FOR_PAPERS_ON_CONFERENCE FOREIGN KEY (conference_id) REFERENCES conferences (id);

ALTER TABLE conferences
    ADD CONSTRAINT FK_CONFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_CONFERENCE FOREIGN KEY (conference_id) REFERENCES conferences (id);

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_DOCUMENT FOREIGN KEY (document_id) REFERENCES documents (id);

ALTER TABLE call_for_papers_topics
    ADD CONSTRAINT fk_calforpaptop_on_call_for_papers FOREIGN KEY (call_for_papers_id) REFERENCES call_for_papers (id);

ALTER TABLE call_for_papers_topics
    ADD CONSTRAINT fk_calforpaptop_on_topic FOREIGN KEY (topics_id) REFERENCES topics (id);

ALTER TABLE submissions_authors
    ADD CONSTRAINT fk_subaut_on_author FOREIGN KEY (authors_id) REFERENCES authors (id);

ALTER TABLE submissions_authors
    ADD CONSTRAINT fk_subaut_on_submission FOREIGN KEY (submission_id) REFERENCES submissions (id);

ALTER TABLE submissions_keywords
    ADD CONSTRAINT fk_subkey_on_keyword FOREIGN KEY (keywords_id) REFERENCES keywords (id);

ALTER TABLE submissions_keywords
    ADD CONSTRAINT fk_subkey_on_submission FOREIGN KEY (submission_id) REFERENCES submissions (id);