ALTER TABLE authors
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE authors
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;