ALTER TABLE conferences DROP CONSTRAINT FK_CONFERENCES_ON_USER;

ALTER TABLE conferences
    ADD CONSTRAINT FK_CONFERENCES_ON_USER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE ;

ALTER  TABLE  call_for_papers DROP CONSTRAINT FK_CALL_FOR_PAPERS_ON_CONFERENCE;

ALTER TABLE call_for_papers
    ADD CONSTRAINT FK_CALL_FOR_PAPERS_ON_CONFERENCE FOREIGN KEY (conference_id)
        REFERENCES conferences (id) ON DELETE CASCADE ;

ALTER TABLE submissions DROP CONSTRAINT FK_SUBMISSIONS_ON_CONFERENCE;

ALTER TABLE submissions
    ADD CONSTRAINT FK_SUBMISSIONS_ON_CONFERENCE FOREIGN KEY (conference_id)
        REFERENCES conferences (id) ON DELETE CASCADE;

ALTER TABLE submissions_authors DROP CONSTRAINT fk_subaut_on_submission;

ALTER TABLE submissions_authors
    ADD CONSTRAINT fk_subaut_on_submission FOREIGN KEY (submission_id) REFERENCES submissions (id) ON DELETE CASCADE;